# VacationPy
----

#### Note
* Keep an eye on your API usage. Use https://developers.google.com/maps/reporting/gmp-reporting as reference for how to monitor your usage and billing.

* Instructions have been included for each segment. You do not have to follow them exactly, but they are included to help you think through the steps.

In [1]:
# Dependencies and Setup
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import requests
import gmaps
import os
from pprint import pprint

# Import API key
from api_keys import g_key
gmaps.configure(api_key=g_key)

outputFilePath = os.path.join("Results-Data")

### Store Part I results into DataFrame
* Load the csv exported in Part I to a DataFrame

In [2]:
Cities_Climate_df = pd.read_csv(os.path.join("Results-Data","Cities_Climate.csv"),delimiter=",")
Cities_Climate_df

,Latitude,Longitude,City,Country,Max Temp,Humidity,Wind Speed,Cloudiness,Date
0,62.69,25.82,aanekoski,fi,46.40,93.0,6.93,90.0,1.603860e+09
1,12.35,29.25,abu zabad,sd,78.39,29.0,8.93,0.0,1.603860e+09
2,16.86,-99.89,acapulco,mx,80.37,84.0,4.72,96.0,1.603859e+09
3,-2.89,-40.12,acarau,br,76.37,87.0,9.46,100.0,1.603860e+09
4,25.75,-1.00,adrar,dz,69.57,23.0,11.63,9.0,1.603860e+09
...,...,...,...,...,...,...,...,...,...
681,47.80,67.71,zhezkazgan,kz,31.08,89.0,13.67,57.0,1.603860e+09
682,66.77,123.37,zhigansk,ru,-2.56,91.0,4.47,73.0,1.603860e+09
683,22.28,113.57,zhuhai,cn,80.60,78.0,9.17,20.0,1.603860e+09
684,51.13,15.92,zlotoryja,pl,39.99,88.0,6.35,71.0,1.603860e+09
685,65.75,150.85,zyryanka,ru,7.88,93.0,4.12,0.0,1.603860e+09

### Humidity Heatmap
* Configure gmaps.
* Use the Lat and Lng as locations and Humidity as the weight.
* Add Heatmap layer to map.

In [3]:
#Pull the locations based on there Latitude and Longitude of each city
locations = Cities_Climate_df[["Latitude","Longitude"]].astype(float)

#Drop any NAN values in case they weren't removed already
Cities_Climate_df = Cities_Climate_df.dropna()

#Use humidity as the float
humidity = Cities_Climate_df["Humidity"].astype(float)
MaxHumidity = humidity.max()

In [4]:
#create a map using humidity and a heatmap layer
heat = gmaps.figure()
heatlayer = gmaps.heatmap_layer(locations, weights = humidity, dissipating=False, max_intensity = MaxHumidity, point_radius = 3)

heat.add_layer(heatlayer)
heat

Figure(layout=FigureLayout(height='420px'))

### Create new DataFrame fitting weather criteria
* Narrow down the cities to fit weather conditions.
* Drop any rows will null values.

In [5]:
Vacation_df = Cities_Climate_df.loc[(Cities_Climate_df["Max Temp"]>70)&
                                    (Cities_Climate_df["Max Temp"]<80)&
                                   (Cities_Climate_df["Cloudiness"]==0)&
                                   (Cities_Climate_df["Wind Speed"]<10)].reset_index(drop=True)
Vacation_df

,Latitude,Longitude,City,Country,Max Temp,Humidity,Wind Speed,Cloudiness,Date
0,12.35,29.25,abu zabad,sd,78.39,29.0,8.93,0.0,1.603860e+09
1,24.09,32.91,aswan,eg,77.95,41.0,7.70,0.0,1.603860e+09
2,12.22,-15.45,bissora,gw,71.04,84.0,0.89,0.0,1.603860e+09
3,-12.79,45.27,dzaoudzi,yt,78.80,78.0,3.36,0.0,1.603860e+09
4,29.56,34.95,elat,il,75.20,38.0,6.93,0.0,1.603859e+09
5,9.36,17.37,goundi,td,72.95,62.0,2.55,0.0,1.603859e+09
6,9.04,-69.74,guanare,ve,73.36,89.0,2.75,0.0,1.603859e+09
7,8.88,11.37,jalingo,ng,72.79,66.0,1.36,0.0,1.603860e+09
8,14.20,24.67,kutum,sd,70.32,29.0,7.87,0.0,1.603860e+09
9,15.62,-16.22,louga,sn,77.00,61.0,4.70,0.0,1.603859e+09
10,18.48,31.82,marawi,sd,79.77,32.0,8.19,0.0,1.603860e+09
11,-16.73,-43.86,montes claros,br,75.20,73.0,9.17,0.0,1.603859e+09
12,-32.50,137.77,port augusta,au,73.00,35.0,8.05,0.0,1.603860e+09
13,17.02,54.09,salalah,om,78.80,54.0,2.24,0.0,1.603860e+09
14,26.04,68.14,sann,pk,73.40,60.0,4.70,0.0,1.603860e+09
15,-10.15,-67.74,senador guiomard,br,71.60,100.0,3.36,0.0,1.603860e+09
16,-18.37,21.85,shakawe,bw,74.39,28.0,7.00,0.0,1.603859e+09
17,13.06,5.24,sokoto,ng,73.89,20.0,6.64,0.0,1.603860e+09
18,22.57,59.53,sur,om,79.14,53.0,4.76,0.0,1.603860e+09
19,22.68,-3.98,taoudenni,ml,73.44,22.0,1.66,0.0,1.603860e+09
20,20.20,1.01,tessalit,ml,73.58,20.0,6.55,0.0,1.603860e+09

### Hotel Map
* Store into variable named `hotel_df`.
* Add a "Hotel Name" column to the DataFrame.
* Set parameters to search for hotels with 5000 meters.
* Hit the Google Places API for each city's coordinates.
* Store the first Hotel result into the DataFrame.
* Plot markers on top of the heatmap.

In [20]:
hotel_df = Vacation_df.loc[:,["Latitude","Longitude","City","Country"]]

HotelName = []
HAddress = []
HRating = []
HLat = []
Hlng = []

for index, row in hotel_df.iterrows():
    CurrentCity = row["City"]
    CurrentCountry = row["Country"]
    
    Target_Coord = f"{row['Latitude']},{row['Longitude']}"
    Target_Radius = 5000
    Type = "Hotel"
    keyword = "Hotel"
    
    #Set Paramaters
    params = {
        "location": Target_Coord,
        "radius": Target_Radius,
        "type": Type,
        "keyword": keyword,
        "key": g_key
    }
    
    url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"
    response = requests.get(url,params=params).json()
    results = response['results']
    
    #print(results)
    
    try:
        HotelName.append(results[0]['name'])
        HAddress.append(results[0]['vicinity'])
        HRating.append(results[0]['rating'])
        HLat.append(results[0]['geometry']['location']['lat'])
        Hlng.append(results[0]['geometry']['location']['lng'])
        print(f"Process records for hotel in {CurrentCity}, {CurrentCountry}")
    except:
        HotelName.append(np.nan)
        HAddress.append(np.nan)
        HRating.append(np.nan)
        HLat.append(np.nan)
        Hlng.append(np.nan)
        print(f"No results for hotel in {CurrentCity}, {CurrentCountry}. Skipping...")

No results for hotel in abu zabad, sd. Skipping...
Process records for hotel in aswan, eg
No results for hotel in bissora, gw. Skipping...
Process records for hotel in dzaoudzi, yt
Process records for hotel in elat, il
No results for hotel in goundi, td. Skipping...
Process records for hotel in guanare, ve
Process records for hotel in jalingo, ng
No results for hotel in kutum, sd. Skipping...
Process records for hotel in louga, sn
Process records for hotel in marawi, sd
Process records for hotel in montes claros, br
Process records for hotel in port augusta, au
Process records for hotel in salalah, om
No results for hotel in sann, pk. Skipping...
Process records for hotel in senador guiomard, br
Process records for hotel in shakawe, bw
Process records for hotel in sokoto, ng
Process records for hotel in sur, om
No results for hotel in taoudenni, ml. Skipping...
No results for hotel in tessalit, ml. Skipping...

In [21]:
# Add columns to hotel_df of the hotels information
hotel_df["Hotel Name"] = HotelName
hotel_df["Address"] = HAddress
hotel_df["Rating"] = HRating
hotel_df["Lat"] = HLat
hotel_df["Lng"] = Hlng

# remove any nan rows
hotel_df = hotel_df.dropna()
hotel_df

,Latitude,Longitude,City,Country,Hotel Name,Address,Rating,Lat,Lng
1,24.09,32.91,aswan,eg,Sofitel Legend Old Cataract Aswan,"Abtal El Tahrir, Street",4.9,24.094242,32.897351
3,-12.79,45.27,dzaoudzi,yt,Oasis hÃ´tel,"97 Rue du Commerce, Mamoudzou",3.0,-12.781890,45.230154
4,29.56,34.95,elat,il,"Al Manara, a Luxury Collection Hotel, Saraya A...","Al-Hashemi St., Aqaba",4.7,29.535782,34.993276
6,9.04,-69.74,guanare,ve,Nuevo Hotel Coromoto,"Carrera 3, Guanare",4.2,9.049820,-69.742937
7,8.88,11.37,jalingo,ng,"Fast Track Hotel, Jalingo","Nyamu Sala Street, behind Muslim Council, Jalingo",4.0,8.895438,11.394187
9,15.62,-16.22,louga,sn,Casa Italia,"City Bagdad No 22, Louga",3.4,15.630843,-16.236025
10,18.48,31.82,marawi,sd,Merowe Tourist Village,"Shirian El Shimal, Merowe",4.3,18.475178,31.810473
11,-16.73,-43.86,montes claros,br,ibis Montes Claros Shopping,"Av. Donato Quintino, 130 - Cidade Nova, Montes...",4.3,-16.740446,-43.870279
12,-32.50,137.77,port augusta,au,Crossroads Ecomotel,"43/47 Eyre Hwy, Port Augusta West",4.7,-32.480949,137.754743
13,17.02,54.09,salalah,om,BAITI Hotel Apartments,"Unnamed Road, Salalah",3.9,17.018337,54.096719
15,-10.15,-67.74,senador guiomard,br,Hotel Rondon,"Av. Castelo Branco, 0980, Sen. Guiomard",3.8,-10.147787,-67.740901
16,-18.37,21.85,shakawe,bw,Drotsky's Cabins,Botswana,4.4,-18.414846,21.880995
17,13.06,5.24,sokoto,ng,Grand Ibro Hotel,"1 Abdulahi Fodio Rd, Sokoto",3.7,13.060457,5.218983
18,22.57,59.53,sur,om,Sur Plaza Hotel,Sur,3.8,22.566435,59.495858

In [22]:
# NOTE: Do not change any of the code in this cell

# Using the template add the hotel marks to the heatmap
info_box_template = """
<dl>
<dt>Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
</dl>
"""
# Store the DataFrame Row
# NOTE: be sure to update with your DataFrame name
hotel_info = [info_box_template.format(**row) for index, row in hotel_df.iterrows()]
locations = hotel_df[["Lat", "Lng"]]

In [26]:
# Add marker layer ontop of heat map
markers = gmaps.marker_layer(locations, info_box_content=hotel_info)
heat.add_layer(markers)
# Display figure
heat

Figure(layout=FigureLayout(height='420px'))